//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdd_quizz_Entities : DbContext
    {
        public bdd_quizz_Entities()
            : base("name=bdd_quizz_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<compte> compte { get; set; }
        public virtual DbSet<question> question { get; set; }
        public virtual DbSet<quizz> quizz { get; set; }
        public virtual DbSet<reponse> reponse { get; set; }
        public virtual DbSet<reponse_candidat> reponse_candidat { get; set; }
        public virtual DbSet<taux_complexite> taux_complexite { get; set; }
    }
}
