//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public permission()
        {
            this.compte = new HashSet<compte>();
        }
    
        public int pk_permission { get; set; }
        public Nullable<sbyte> generer_quizz { get; set; }
        public Nullable<sbyte> ajouter_quest { get; set; }
        public Nullable<sbyte> modifier_quest { get; set; }
        public Nullable<sbyte> suppr_question { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compte> compte { get; set; }
    }
}
