//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personnage()
        {
            this.skill = new HashSet<skill>();
        }
    
        public int pk_personnage { get; set; }
        public string nom { get; set; }
        public Nullable<float> vie { get; set; }
        public Nullable<float> degat { get; set; }
        public Nullable<float> defense { get; set; }
        public Nullable<int> nb_round { get; set; }
        public Nullable<int> id_groupe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skill> skill { get; set; }
    }
}
