//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reponse_candidat
    {
        public int id_reponse { get; set; }
        public string reponse { get; set; }
        public string commentaire { get; set; }
        public int fk_question { get; set; }
    
        public virtual question question { get; set; }
    }
}
