//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reponse_candidat
    {
        public int pk_reponse { get; set; }
        public string reponse { get; set; }
        public string commentaire { get; set; }
        public int fk_compte { get; set; }
        public int fk_question { get; set; }
    
        public virtual compte compte { get; set; }
        public virtual question question { get; set; }
    }
}
