//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public int pk_skill { get; set; }
        public Nullable<float> frequence { get; set; }
        public Nullable<int> degat { get; set; }
        public string nom { get; set; }
        public Nullable<int> type { get; set; }
        public int personnage_idpersonnage { get; set; }
    
        public virtual personnage personnage { get; set; }
    }
}
